apiVersion: apps/v1
kind: Deployment
metadata:
  name: dice-roller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dice-roller
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-python: "true"
      labels:
        app.kubernetes.io/name: "dice-roller"
        app.kubernetes.io/version: "1.0.0"
        app.kubernetes.io/part-of: "operator-demo"
    spec:
      containers:
      - name: dice-roller
        image: ghcr.io/rb3ckers/dice-roller-app:python
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: dice-roller
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app.kubernetes.io/name: dice-roller